# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: "Kekn9ne's Personal Blog"
email: kekn9ne@yandex.com
tagline: "Welcome to My Personal Programming Journey"
description: >- # this means to ignore newlines until "baseurl:"
  Welcome to my personal tech blog where I share insights about programming, 
  development, and technology. Follow my journey through GitHub projects, 
  coding tutorials, and tech discussions. Connect with me on Twitter and GitHub 
  for more tech conversations.
baseurl: "/blog" # the subpath of your site, e.g. /blog
url: "https://kekn9ne.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: aytgdmr
github_username: kekn9ne  # Replace with your GitHub username
comments: true  # Enable comments by default on all posts

# Author and Social Settings
author:
  name: kekn9ne
  twitter: aytgdmr
  github: kekn9ne

# Social Media Settings
twitter:
  username: aytgdmr
  card: summary_large_image

social:
  name: kekn9ne
  links:
    - https://github.com/kekn9ne
    - https://twitter.com/jekyllrb

# Logo and Branding
logo: "https://kekn9ne.github.io/blog/assets/images/logo.png"

# Language Settings
locale: en_US

# Webmaster Verifications
webmaster_verifications:
  google: rHRMPnXg71SiALT-UWkSNjxeYvXeGgeAj_RpIHjDR8Y  # Get from Google Search Console
  bing: YOUR_BING_VERIFICATION_CODE      # Get from Bing Webmaster Tools
  yandex: YOUR_YANDEX_VERIFICATION_CODE  # Optional: Get from Yandex Webmaster
  baidu: YOUR_BAIDU_VERIFICATION_CODE    # Optional: Get from Baidu Webmaster

# Default Settings for Posts
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      image: 
        path: "https://kekn9ne.github.io/blog/assets/images/default-social.jpg"
        width: 1200
        height: 1200
      author: kekn9ne
      locale: en_US
      tags: []  # Empty array as default
      seo:
        type: "BlogPosting"

# Build settings
# theme: minima  # Commented out as we're using our custom theme
plugins:
  - jekyll-feed
  - jekyll-admin
  - jekyll-seo-tag
  - jekyll-sitemap

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Comments settings
cusdis:
  app_id: "8def4212-5f52-4205-900b-a0af219a1d42" # Replace this with the app_id from your Cusdis admin panel
  host: "https://blog.kekn9ne.duckdns.org"
commento:
  url: "https://yourblog-comments.duckdns.org"

# Prose.io settings
prose:
  rooturl: '_posts'
  siteurl: 'https://kekn9ne.github.io/blog'
  media: 'assets/images'
  ignore:
    - index.markdown
    - _config.yml
    - /_layouts
    - /_includes
    - /css
    - /assets
    - /js
    - README.md
    - .gitignore
    - Gemfile
    - Gemfile.lock
  metadata:
    _posts:
      - name: "layout"
        field:
          element: "hidden"
          value: "post"
      - name: "title"
        field:
          element: "text"
          label: "Post Title"
          placeholder: "Enter a descriptive title for your post"
          help: "Choose a clear, engaging title that describes your post content"
      - name: "description"
        field:
          element: "textarea"
          label: "Description"
          placeholder: "Brief description of your post (max 160 characters)"
          help: "Write a compelling meta description to improve SEO"
      - name: "date"
        field:
          element: "text"
          label: "Publication Date"
          value: CURRENT_DATETIME
          help: "Current date and time will be automatically set"
      - name: "author"
        field:
          element: "hidden"
          value: CURRENT_USER
      - name: "categories"
        field:
          element: "select"
          label: "Category"
          placeholder: "Choose a primary category"
          options:
            - name: "Programming"
              value: "programming"
            - name: "Technology"
              value: "technology"
            - name: "Tutorials"
              value: "tutorials"
            - name: "Projects"
              value: "projects"
            - name: "Development"
              value: "development"
      - name: "tags"
        field:
          element: "text"
          label: "Tags"
          placeholder: "javascript, react, tutorial"
          help: "Add relevant tags separated by commas"
          alterable: true
      - name: "image"
        field:
          element: "text"
          label: "Featured Image"
          placeholder: "/assets/images/your-image.jpg"
          help: "Add a featured image path (recommended size: 1200x630px)"
      - name: "comments"
        field:
          element: "button"
          label: "Comments"
          help: "Toggle comments for this post"
          on: "true"
          off: "false"

# Sitemap settings
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      sitemap:
        changefreq: "weekly"
        priority: 0.8
  - scope:
      path: ""
      type: "pages"
    values:
      sitemap:
        changefreq: "monthly"
        priority: 0.5

# URL handling
url: "https://kekn9ne.github.io"
baseurl: "/blog"
permalink: /:year/:month/:day/:title/

# Force www/non-www (uncomment one)
enforce_ssl: kekn9ne.github.io   # Forces HTTPS and canonical URL
