# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: My Blog
email: kekn9ne@yandex.com
tagline: A journey through technology, programming, and personal growth
description: >- # this means to ignore newlines until "baseurl:"
  A personal space where I share my journey through technology, programming, 
  and life experiences. From tech deep dives and coding adventures to 
  thoughts on personal growth, join me in exploring the world of modern development.
baseurl: "/blog" # the subpath of your site, e.g. /blog
url: "https://kekn9ne.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: aytgdmr
github_username: kekn9ne  # Replace with your GitHub username
comments: true  # Enable comments by default on all posts

# Author and Social Settings
author:
  name: kekn9ne
  twitter: aytgdmr
  github: kekn9ne

# Social Media Settings
twitter:
  username: aytgdmr
  card: summary_large_image

social:
  name: kekn9ne
  links:
    - https://github.com/kekn9ne
    - https://twitter.com/jekyllrb

# Logo and Branding
logo: /assets/images/logo.png

# Language Settings
locale: en_US

# Webmaster Verifications
webmaster_verifications:
  google: rHRMPnXg71SiALT-UWkSNjxeYvXeGgeAj_RpIHjDR8Y  # Get from Google Search Console
  bing: YOUR_BING_VERIFICATION_CODE      # Get from Bing Webmaster Tools
  yandex: YOUR_YANDEX_VERIFICATION_CODE  # Optional: Get from Yandex Webmaster
  baidu: YOUR_BAIDU_VERIFICATION_CODE    # Optional: Get from Baidu Webmaster

# Default Settings for Posts
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      image: 
        path: /assets/images/default-social.jpg
        width: 1200
        height: 1200
      author: kekn9ne
      locale: en_US

# Build settings
# theme: minima  # Commented out as we're using our custom theme
plugins:
  - jekyll-feed
  - jekyll-admin
  - jekyll-seo-tag

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Comments settings
cusdis:
  app_id: "8def4212-5f52-4205-900b-a0af219a1d42" # Replace this with the app_id from your Cusdis admin panel
  host: "https://blog.kekn9ne.duckdns.org"
commento:
  url: "https://yourblog-comments.duckdns.org"

# Prose.io settings
prose:
  rooturl: '_posts'
  siteurl: 'https://kekn9ne.github.io/blog'
  media: 'assets/images'
  metadata:
    _posts:
      - name: "layout"
        field:
          element: "hidden"
          value: "post"
      - name: "title"
        field:
          element: "text"
          label: "Post title"
          placeholder: "Enter your post title"
      - name: "date"
        field:
          element: "text"
          label: "Date"
          value: CURRENT_DATETIME
      - name: "categories"
        field:
          element: "multiselect"
          label: "Add categories"
          placeholder: "Choose categories"
          options:
            - name: "Technology"
              value: "technology"
            - name: "Programming"
              value: "programming"
            - name: "Personal"
              value: "personal"
      - name: "comments"
        field:
          element: "checkbox"
          label: "Allow comments"
          value: true
